"""empty message

Revision ID: 29278680665d
Revises: 811717de55ce
Create Date: 2023-11-19 11:59:00.138934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29278680665d'
down_revision = '811717de55ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_months', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('selected_crops', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('selected_crops')
        batch_op.drop_column('selected_months')

    # ### end Alembic commands ###
