"""empty message

Revision ID: 537d6d577d9d
Revises: 29278680665d
Create Date: 2023-11-19 14:38:25.270405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537d6d577d9d'
down_revision = '29278680665d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
