"""Add avatar_url to UserModel

Revision ID: 811717de55ce
Revises: a56e35f67323
Create Date: 2023-11-18 23:37:50.193955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811717de55ce'
down_revision = 'a56e35f67323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
